# Generated by Django 2.2.2 on 2019-06-20 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.College')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('prof_name', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('pre_req', models.CharField(default='', max_length=100)),
                ('materials', models.CharField(default='', max_length=100)),
                ('anonymous', models.BooleanField(choices=[(False, 'False'), (True, 'True:Your username is NOT recorded.You CANNOT modify this review later!!')], default=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('assessment', models.CharField(choices=[('PS', 'Problem sets'), ('PJ', 'Projects'), ('PR', 'Presentations'), ('EX', 'Exams'), ('PP', 'Papers')], default='EX', max_length=2)),
                ('class_size', models.CharField(choices=[('S', 'Small:1-10'), ('M', 'Medium:10-20'), ('L', 'Large:20+')], default='M', max_length=1)),
                ('work_load', models.CharField(choices=[('L', 'Light:<=3 hours/week'), ('M', 'Medium:<=6 hours/week'), ('H', 'Heavy:<=10 hours/week'), ('I', 'Insane:>10 hours/week')], default='M', max_length=2)),
                ('diff_level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('I', 'Insane')], default='M', max_length=1)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.College')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Restaurant')),
                ('users_liked', models.ManyToManyField(related_name='users_liked', to=settings.AUTH_USER_MODEL)),
                ('users_reported', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
