# Generated by Django 2.2.2 on 2019-06-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='assessment',
        ),
    ]
