# Generated by Django 2.2.2 on 2019-06-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='assessment',
            field=models.CharField(choices=[('TB', 'Test-based'), ('MI', 'Mixed'), ('PB', 'Project-based')], default='MI', max_length=2),
        ),
    ]
