# Generated by Django 2.2.2 on 2019-06-21 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190621_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sub',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
