# Generated by Django 2.2.2 on 2019-06-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='assessment',
        ),
        migrations.AddField(
            model_name='review',
            name='prof_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
