# Generated by Django 2.2.2 on 2019-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190619_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='school',
            field=models.CharField(choices=[('HC', 'Haverford'), ('BMC', 'Bryn Mawr'), ('SW', 'Swarthmore')], default='HC', max_length=3),
        ),
        migrations.AddField(
            model_name='review',
            name='assessment',
            field=models.CharField(choices=[('PS', 'Problem sets'), ('PJ', 'Projects'), ('PR', 'Presentations'), ('EX', 'Exams'), ('PP', 'Papers')], default='EX', max_length=2),
        ),
        migrations.AddField(
            model_name='review',
            name='class_size',
            field=models.CharField(choices=[('S', 'Small:1-10'), ('M', 'Medium:10-20'), ('L', 'Large:20+')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='review',
            name='work_load',
            field=models.CharField(choices=[('L', 'Light:<=3 hours/week'), ('M', 'Medium:<=6 hours/week'), ('H', 'Heavy:<=10 hours/week'), ('I', 'Insane:>10 hours/week')], default='M', max_length=2),
        ),
    ]
