# Generated by Django 2.2.2 on 2019-06-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190619_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='diff_level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('I', 'Insane')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='review',
            name='materials',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='pre_req',
            field=models.CharField(default='', max_length=100),
        ),
    ]
