# Generated by Django 2.2.2 on 2019-06-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_comment_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField(choices=[(False, 'False'), (True, 'True:Your username is NOT recorded.You CANNOT modify this review later!!')], default=False)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField(choices=[(False, 'False'), (True, 'True:Your username is NOT recorded.You CANNOT modify this review later!!')], default=False)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Department')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='response',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Topic'),
        ),
    ]
