# Generated by Django 2.2.2 on 2019-06-19 16:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reviews', '0006_auto_20190619_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(to='reviews.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='report_review',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
