# Generated by Django 2.2.2 on 2019-06-19 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('reviews', '0007_auto_20190619_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='report',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
