# Generated by Django 2.2.2 on 2019-06-26 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked_response', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='users_reported',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked_topic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='users_reported',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
