# Generated by Django 2.2.2 on 2019-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20190626_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assessment',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='diff_level',
            field=models.IntegerField(choices=[(1, 'VeryEasy'), (2, 'Easy'), (3, 'Manageable'), (4, 'Challenging'), (5, 'Suffocating')], default=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
