# Generated by Django 2.2.2 on 2019-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20190619_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grad_year',
            field=models.IntegerField(),
        ),
    ]
