# Generated by Django 2.2.2 on 2019-06-19 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0014_auto_20190619_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='report',
        ),
        migrations.AddField(
            model_name='review',
            name='users_reported',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
