# Generated by Django 2.2.2 on 2019-06-29 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0015_auto_20190629_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user_name',
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ManyToManyField(related_name='response_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ManyToManyField(related_name='topic_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
