# Generated by Django 2.2.2 on 2019-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20190629_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='review',
            name='college',
        ),
        migrations.AddField(
            model_name='review',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus'),
        ),
    ]
