# Generated by Django 2.2.2 on 2019-06-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20190629_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='act_date',
            field=models.DateTimeField(null=True, verbose_name='last active'),
        ),
    ]
