# Generated by Django 2.2.2 on 2019-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_topic_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='act_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last active'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
