# Generated by Django 2.2.2 on 2019-07-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20190701_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='act_date',
            new_name='pub_date',
        ),
    ]
