# Generated by Django 2.2.2 on 2019-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20190701_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
